title: Moltbot
email: contact@moltbotcase.com
description: >-
  The ultimate guide to Moltbot.
baseurl: ""
url: "https://moltbotcase.com"

markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: ""
    values:
      layout: default
